services:
  db:
    container_name: company-lens-db
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
      
  redis:
    container_name: company-lens-redis
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data: