# Generated by Django 5.2.1 on 2025-05-23 00:12

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ticker', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.CharField(default=core.utils.generate_id, max_length=24, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='company_documents/')),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('key_points', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.CharField(default=core.utils.generate_id, max_length=24, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('headquarters', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_count', models.CharField(blank=True, max_length=50, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('crunchbase_url', models.URLField(blank=True, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('annual_revenue', models.CharField(blank=True, max_length=100, null=True)),
                ('funding_total', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('financial_health_score', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('business_risk_score', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('growth_potential_score', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('industry_position_score', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('external_trends_score', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('overall_score', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('financial_health_insight', models.TextField(blank=True, null=True)),
                ('business_risk_insight', models.TextField(blank=True, null=True)),
                ('growth_potential_insight', models.TextField(blank=True, null=True)),
                ('industry_position_insight', models.TextField(blank=True, null=True)),
                ('external_trends_insight', models.TextField(blank=True, null=True)),
                ('overall_insight', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='companies.company')),
            ],
        ),
    ]
