# Generated by Django 5.2.1 on 2025-05-24 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
        ('compare', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparisonsession',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='comparisonsession',
            name='workspace',
        ),
        migrations.CreateModel(
            name='ComparisonTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('task_type', models.CharField(choices=[('general', 'General Comparison'), ('financial', 'Financial Comparison')], default='general', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cache_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('companies', models.ManyToManyField(related_name='comparison_tasks', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_tasks', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_tasks', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CompanyInComparison',
        ),
        migrations.DeleteModel(
            name='ComparisonSession',
        ),
    ]
