# Generated by Django 5.2.1 on 2025-05-24 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
        ('compare', '0002_remove_comparisonsession_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonresult',
            name='comparison_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparisonresult',
            name='content_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparisonresult',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparisontask',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparisontask',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comparisontask',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparisontask',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='compare.comparisonresult'),
        ),
        migrations.AlterField(
            model_name='comparisontask',
            name='task_type',
            field=models.CharField(choices=[('general', 'General Comparison'), ('financial', 'Financial Analysis'), ('competitive', 'Competitive Analysis')], default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='ComparisonMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('financial', 'Financial Metrics'), ('growth', 'Growth Metrics'), ('risk', 'Risk Metrics'), ('market', 'Market Position'), ('custom', 'Custom Metrics')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('comparison_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='compare.comparisonresult')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyMetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_values', to='companies.company')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='compare.comparisonmetric')),
            ],
        ),
    ]
