# Generated by Django 5.2.1 on 2025-05-24 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0004_remove_comparisonmetric_comparison_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparisontask',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='comparisontask',
            name='notes',
        ),
    ]
