# Generated by Django 5.2.1 on 2025-05-24 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0006_comparisontask_result_html'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComparisonResult',
        ),
        migrations.DeleteModel(
            name='ComparisonTask',
        ),
    ]
