# Generated by Django 5.2.1 on 2025-05-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspacecompany',
            old_name='added_at',
            new_name='created_at',
        ),
    ]
